-- =========================================================================
-- ACCESORIOS LILÍS: SCRIPT DE ACTUALIZACIÓN TOTAL DE ESQUEMA EN PRODUCCIÓN
-- Este script agrega de forma segura todas las columnas nuevas sin borrar datos.
-- Puedes ejecutarlo en MySQL Workbench, phpMyAdmin, Clever Cloud, Render o Railway.
-- =========================================================================

-- 1. TABLA USERS (Usuarios y Administradores)
CREATE TABLE IF NOT EXISTS `Users` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Email` VARCHAR(150) NOT NULL,
    `FullName` VARCHAR(150) NOT NULL,
    `Role` VARCHAR(50) NOT NULL DEFAULT 'Customer',
    `PictureUrl` VARCHAR(500) NULL,
    `PasswordHash` VARCHAR(255) NULL,
    `LastLoginAt` DATETIME NULL,
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NULL,
    `DeletedAt` DATETIME NULL,
    PRIMARY KEY (`Id`),
    UNIQUE KEY `IX_Users_Email` (`Email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Agregar columnas en Users si faltan
SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Users' AND COLUMN_NAME='PasswordHash');
SET @s = IF(@c=0, 'ALTER TABLE `Users` ADD COLUMN `PasswordHash` VARCHAR(255) NULL;', 'SELECT 1;');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Users' AND COLUMN_NAME='LastLoginAt');
SET @s = IF(@c=0, 'ALTER TABLE `Users` ADD COLUMN `LastLoginAt` DATETIME NULL;', 'SELECT 1;');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Users' AND COLUMN_NAME='PictureUrl');
SET @s = IF(@c=0, 'ALTER TABLE `Users` ADD COLUMN `PictureUrl` VARCHAR(500) NULL;', 'SELECT 1;');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Users' AND COLUMN_NAME='Role');
SET @s = IF(@c=0, 'ALTER TABLE `Users` ADD COLUMN `Role` VARCHAR(50) NOT NULL DEFAULT \'Customer\';', 'SELECT 1;');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- 2. TABLA PRODUCTS (Catálogo e Inventario)
CREATE TABLE IF NOT EXISTS `Products` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(200) NOT NULL,
    `Category` VARCHAR(100) NULL,
    `Price` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `Stock` INT NOT NULL DEFAULT 10,
    `ImageUrl` LONGTEXT NULL,
    `Description` TEXT NULL,
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NULL,
    `DeletedAt` DATETIME NULL,
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Modificar ImageUrl para soportar imágenes largas o base64
ALTER TABLE `Products` MODIFY COLUMN `ImageUrl` LONGTEXT NULL;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Products' AND COLUMN_NAME='Stock');
SET @s = IF(@c=0, 'ALTER TABLE `Products` ADD COLUMN `Stock` INT NOT NULL DEFAULT 10;', 'SELECT 1;');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Products' AND COLUMN_NAME='Description');
SET @s = IF(@c=0, 'ALTER TABLE `Products` ADD COLUMN `Description` TEXT NULL;', 'SELECT 1;');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Products' AND COLUMN_NAME='Category');
SET @s = IF(@c=0, 'ALTER TABLE `Products` ADD COLUMN `Category` VARCHAR(100) NULL;', 'SELECT 1;');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- 3. TABLA CATEGORIES
CREATE TABLE IF NOT EXISTS `Categories` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(100) NOT NULL,
    `Description` TEXT NULL,
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NULL,
    `DeletedAt` DATETIME NULL,
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. TABLA CUSTOMERS (Clientes)
CREATE TABLE IF NOT EXISTS `Customers` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `FullName` VARCHAR(150) NOT NULL,
    `Phone` VARCHAR(30) NULL,
    `City` VARCHAR(150) NULL,
    `Notes` TEXT NULL,
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NULL,
    `DeletedAt` DATETIME NULL,
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Customers' AND COLUMN_NAME='City');
SET @s = IF(@c=0, 'ALTER TABLE `Customers` ADD COLUMN `City` VARCHAR(150) NULL;', 'SELECT 1;');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Customers' AND COLUMN_NAME='Notes');
SET @s = IF(@c=0, 'ALTER TABLE `Customers` ADD COLUMN `Notes` TEXT NULL;', 'SELECT 1;');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- 5. TABLA ORDERS (Pedidos)
CREATE TABLE IF NOT EXISTS `Orders` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `CustomerId` INT NOT NULL,
    `Total` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `Status` VARCHAR(50) NOT NULL DEFAULT 'Pendiente',
    `Notes` TEXT NULL,
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NULL,
    `DeletedAt` DATETIME NULL,
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Orders' AND COLUMN_NAME='Status');
SET @s = IF(@c=0, 'ALTER TABLE `Orders` ADD COLUMN `Status` VARCHAR(50) NOT NULL DEFAULT \'Pendiente\';', 'SELECT 1;');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Orders' AND COLUMN_NAME='Notes');
SET @s = IF(@c=0, 'ALTER TABLE `Orders` ADD COLUMN `Notes` TEXT NULL;', 'SELECT 1;');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Orders' AND COLUMN_NAME='Total');
SET @s = IF(@c=0, 'ALTER TABLE `Orders` ADD COLUMN `Total` DECIMAL(18,2) NOT NULL DEFAULT 0;', 'SELECT 1;');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;

-- 6. TABLA ORDERITEMS (Detalle de Pedidos)
CREATE TABLE IF NOT EXISTS `OrderItems` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `OrderId` INT NOT NULL,
    `ProductId` INT NOT NULL,
    `Quantity` INT NOT NULL DEFAULT 1,
    `UnitPrice` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NULL,
    `DeletedAt` DATETIME NULL,
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SELECT 'Base de datos sincronizada y actualizada correctamente!' AS Resultado;
